package com.copper.communicator;

public interface RequestResponseType {
	int REQUEST_TYPE_LOGIN = 01;
	int REQUEST_TYPE_FORGOT = 02;
	int REQUEST_TYPE_JOB = 03;
	int REQUEST_TYPE_CREATE_JOB = 05;
	int REQUEST_TYPE_DELETE_JOB = 06;

	int REQUEST_TYPE_INVENTORIES = 04;
	int REQUEST_TYPE_CREATE_INVENTORY = 07;
	int REQUEST_TYPE_DELETE_INVENTORY = 8;
	int REQUEST_TYPE_CLIENT = 9;
	int REQUEST_TYPE_CREATE_CLIENT = 10;
	int REQUEST_TYPE_DELETE_CLIENT = 11;
	int REQUEST_TYPE_CREATE_PROPERTY = 12;
	int REQUEST_TYPE_DELETE_PROPERTY = 13;
	int REQUEST_TYPE_CREATE_QUOTE = 14;
	int REQUEST_TYPE_QUOTE = 15;
	int REQUEST_TYPE_PROPERTY = 16;
	int REQUEST_TYPE_EXPANSES = 17;
	int REQUEST_TYPE_CREATE_EXPANSES = 18;
	int REQUEST_TYPE_CREATE_TASK = 19;
	int REQUEST_TYPE_TASK = 20;
	int REQUEST_TYPE_TODAY_TASK = 21;
	int REQUEST_TYPE_UPDATE_INVENTORY = 22;
	int REQUEST_TYPE_UPDATE_CLIENT = 23;
	int REQUEST_TYPE_UPDATE_TASK = 24;
	int REQUEST_TYPE_UPDATE_EXPANSES = 25;
	int REQUEST_TYPE_UPDATE_QUOTE = 26;
	int REQUEST_TYPE_UPDATE_JOB = 27;
	int REQUEST_TYPE_UPDATE_PROPERTY = 28;
	int REQUEST_TYPE_GET_INVOICE = 29;
	int REQUEST_TYPE_CREATE_INVOICE = 30;
	int REQUEST_TYPE_UPDATE_INVOICE = 31;
	int REQUEST_TYPE_GET_CLIENT_PROPERTY = 32;
	int REQUEST_TYPE_CREATE_TIMESHEET = 33;
	int REQUEST_TYPE_UPDATE_TIMESHEET = 34;
	int REQUEST_TYPE_TIMESHEET = 35;
	int REQUEST_TYPE_ROUTE = 36;

}
